/* Generated By:JJTree&JavaCC: Do not edit this line. CDBConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CDBConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int BEGIN = 9;
  /** RegularExpression Id. */
  int END = 10;
  /** RegularExpression Id. */
  int PROGRAM = 11;
  /** RegularExpression Id. */
  int VAR = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int ELSE = 14;
  /** RegularExpression Id. */
  int TRUE = 15;
  /** RegularExpression Id. */
  int FALSE = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int FOR = 18;
  /** RegularExpression Id. */
  int DO = 19;
  /** RegularExpression Id. */
  int INSERT = 20;
  /** RegularExpression Id. */
  int INTO = 21;
  /** RegularExpression Id. */
  int VALUES = 22;
  /** RegularExpression Id. */
  int CREATE = 23;
  /** RegularExpression Id. */
  int REMOVE = 24;
  /** RegularExpression Id. */
  int SELECT = 25;
  /** RegularExpression Id. */
  int STRING = 26;
  /** RegularExpression Id. */
  int INT = 27;
  /** RegularExpression Id. */
  int REAL = 28;
  /** RegularExpression Id. */
  int BOOLEAN = 29;
  /** RegularExpression Id. */
  int COLON = 30;
  /** RegularExpression Id. */
  int EQUALS = 31;
  /** RegularExpression Id. */
  int EE = 32;
  /** RegularExpression Id. */
  int NE = 33;
  /** RegularExpression Id. */
  int LT = 34;
  /** RegularExpression Id. */
  int LE = 35;
  /** RegularExpression Id. */
  int GT = 36;
  /** RegularExpression Id. */
  int GE = 37;
  /** RegularExpression Id. */
  int COMMA = 38;
  /** RegularExpression Id. */
  int DOT = 39;
  /** RegularExpression Id. */
  int SEMICOLON = 40;
  /** RegularExpression Id. */
  int PLUS = 41;
  /** RegularExpression Id. */
  int MINUS = 42;
  /** RegularExpression Id. */
  int STAR = 43;
  /** RegularExpression Id. */
  int SLASH = 44;
  /** RegularExpression Id. */
  int QUOTE = 45;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE = 46;
  /** RegularExpression Id. */
  int LEFT_PAREN = 47;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 48;
  /** RegularExpression Id. */
  int LEFT_BRACE = 49;
  /** RegularExpression Id. */
  int RIGHT_BRACE = 50;
  /** RegularExpression Id. */
  int AND = 51;
  /** RegularExpression Id. */
  int OR = 52;
  /** RegularExpression Id. */
  int IDENTIFIER = 53;
  /** RegularExpression Id. */
  int STRING_LIT = 54;
  /** RegularExpression Id. */
  int INT_LIT = 55;
  /** RegularExpression Id. */
  int REAL_LIT = 56;
  /** RegularExpression Id. */
  int LETTER = 57;
  /** RegularExpression Id. */
  int DIGIT = 58;
  /** RegularExpression Id. */
  int SIGN = 59;
  /** RegularExpression Id. */
  int UNSIGNED_NUMBER = 60;
  /** RegularExpression Id. */
  int WHOLE = 61;
  /** RegularExpression Id. */
  int FRACTION = 62;
  /** RegularExpression Id. */
  int EXPONENT = 63;
  /** RegularExpression Id. */
  int ERROR = 64;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "<token of kind 7>",
    "\"*/\"",
    "\"BEGIN\"",
    "\"END\"",
    "\"PROGRAM\"",
    "\"VAR\"",
    "\"IF\"",
    "\"ELSE\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"WHILE\"",
    "\"FOR\"",
    "\"DO\"",
    "\"INSERT\"",
    "\"INTO\"",
    "\"VALUES\"",
    "\"CREATE\"",
    "\"REMOVE\"",
    "\"SELECT\"",
    "\"STRING\"",
    "\"INT\"",
    "\"REAL\"",
    "\"BOOLEAN\"",
    "\":\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"&&\"",
    "\"||\"",
    "<IDENTIFIER>",
    "<STRING_LIT>",
    "<INT_LIT>",
    "<REAL_LIT>",
    "<LETTER>",
    "<DIGIT>",
    "<SIGN>",
    "<UNSIGNED_NUMBER>",
    "<WHOLE>",
    "<FRACTION>",
    "<EXPONENT>",
    "<ERROR>",
  };

}
