/* Generated By:JJTree&JavaCC: Do not edit this line. CDBConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CDBConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int TRUE = 11;
  /** RegularExpression Id. */
  int FALSE = 12;
  /** RegularExpression Id. */
  int WHILE = 13;
  /** RegularExpression Id. */
  int FOR = 14;
  /** RegularExpression Id. */
  int DO = 15;
  /** RegularExpression Id. */
  int STRING = 16;
  /** RegularExpression Id. */
  int INT = 17;
  /** RegularExpression Id. */
  int REAL = 18;
  /** RegularExpression Id. */
  int BOOLEAN = 19;
  /** RegularExpression Id. */
  int COLON = 20;
  /** RegularExpression Id. */
  int EQUALS = 21;
  /** RegularExpression Id. */
  int EE = 22;
  /** RegularExpression Id. */
  int NE = 23;
  /** RegularExpression Id. */
  int LT = 24;
  /** RegularExpression Id. */
  int LE = 25;
  /** RegularExpression Id. */
  int GT = 26;
  /** RegularExpression Id. */
  int GE = 27;
  /** RegularExpression Id. */
  int COMMA = 28;
  /** RegularExpression Id. */
  int DOT = 29;
  /** RegularExpression Id. */
  int SEMICOLON = 30;
  /** RegularExpression Id. */
  int PLUS = 31;
  /** RegularExpression Id. */
  int MINUS = 32;
  /** RegularExpression Id. */
  int STAR = 33;
  /** RegularExpression Id. */
  int SLASH = 34;
  /** RegularExpression Id. */
  int QUOTE = 35;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE = 36;
  /** RegularExpression Id. */
  int LEFT_PAREN = 37;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 38;
  /** RegularExpression Id. */
  int LEFT_BRACE = 39;
  /** RegularExpression Id. */
  int RIGHT_BRACE = 40;
  /** RegularExpression Id. */
  int AND = 41;
  /** RegularExpression Id. */
  int OR = 42;
  /** RegularExpression Id. */
  int IDENTIFIER = 43;
  /** RegularExpression Id. */
  int STRING_LIT = 44;
  /** RegularExpression Id. */
  int INT_LIT = 45;
  /** RegularExpression Id. */
  int REAL_LIT = 46;
  /** RegularExpression Id. */
  int LETTER = 47;
  /** RegularExpression Id. */
  int DIGIT = 48;
  /** RegularExpression Id. */
  int SIGN = 49;
  /** RegularExpression Id. */
  int UNSIGNED_NUMBER = 50;
  /** RegularExpression Id. */
  int WHOLE = 51;
  /** RegularExpression Id. */
  int FRACTION = 52;
  /** RegularExpression Id. */
  int EXPONENT = 53;
  /** RegularExpression Id. */
  int ERROR = 54;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "<token of kind 7>",
    "\"*/\"",
    "\"IF\"",
    "\"ELSE\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"WHILE\"",
    "\"FOR\"",
    "\"DO\"",
    "\"STRING\"",
    "\"INT\"",
    "\"REAL\"",
    "\"BOOLEAN\"",
    "\":\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"&&\"",
    "\"||\"",
    "<IDENTIFIER>",
    "<STRING_LIT>",
    "<INT_LIT>",
    "<REAL_LIT>",
    "<LETTER>",
    "<DIGIT>",
    "<SIGN>",
    "<UNSIGNED_NUMBER>",
    "<WHOLE>",
    "<FRACTION>",
    "<EXPONENT>",
    "<ERROR>",
  };

}
