/* Generated By:JavaCC: Do not edit this line. CDBTreeConstants.java Version 5.0 */
public interface CDBTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCOMPOUNDSTATEMENT = 1;
  public int JJTVOID = 2;
  public int JJTWHILELOOP = 3;
  public int JJTFORLOOP = 4;
  public int JJTDOLOOP = 5;
  public int JJTIFSTATEMENT = 6;
  public int JJTASSIGNMENTSTATEMENT = 7;
  public int JJTEE = 8;
  public int JJTNE = 9;
  public int JJTLT = 10;
  public int JJTLE = 11;
  public int JJTGT = 12;
  public int JJTGE = 13;
  public int JJTADD = 14;
  public int JJTSUBTRACT = 15;
  public int JJTOR = 16;
  public int JJTMULTIPLY = 17;
  public int JJTDIVIDE = 18;
  public int JJTAND = 19;
  public int JJTNEGATE = 20;
  public int JJTVARIABLE = 21;
  public int JJTINTEGERCONSTANT = 22;
  public int JJTREALCONSTANT = 23;
  public int JJTBOOLEANCONSTANT = 24;
  public int JJTSTRINGCONSTANT = 25;


  public String[] jjtNodeName = {
    "program",
    "compoundStatement",
    "void",
    "whileLoop",
    "forLoop",
    "doLoop",
    "ifStatement",
    "assignmentStatement",
    "EE",
    "NE",
    "LT",
    "LE",
    "GT",
    "GE",
    "add",
    "subtract",
    "or",
    "multiply",
    "divide",
    "and",
    "negate",
    "variable",
    "integerConstant",
    "realConstant",
    "booleanConstant",
    "stringConstant",
  };
}
/* JavaCC - OriginalChecksum=cd1dfce37514fe4e5883378230069732 (do not edit this line) */
